language: node_js

services:
  - docker

before_install:
  - docker pull nmonst4/opsi
  - docker run -itd --name docker-opsi -h opsi.docker.lan -p 4447:4447 -e OPSI_USER=opsi -e OPSI_PASSWORD=opsi nmonst4/opsi
  - docker exec docker-opsi /usr/local/bin/entrypoint.sh

before_script:
  - nvm install --lts
  - npm install -g codecov nyc
  - npm install

script:
  - nyc mocha && codecov
#  - npm test
