language: node_js

jobs:
  include:
    - stage: test
      services:
        - docker

      before_install:
        - docker pull nmonst4/opsi
        - docker run -itd --name docker-opsi -h opsi.docker.lan -p 4447:4447 -e OPSI_USER=opsi -e OPSI_PASSWORD=opsi nmonst4/opsi
        - docker exec docker-opsi /usr/local/bin/entrypoint.sh
        - docker exec docker-opsi opsi-product-updater -i -vv -p hwaudit,swaudit

      before_script:
        - nvm install --lts
        - npm install -g codecov
        - npm install

      script:
        - npm run create-coverage
        - npm run report-coverage
      #  - npm test
    #- stage: build_docs
    #  install:
    #    - npm install
    #    - npm install -g vuepress
    #  script:
    #    - npm run docs:build
    #  cache:
    #    directories:
    #      - "node_modules"
    #  notifications:
    #    email: false
